# Generated by Django 5.0.4 on 2024-04-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='last_name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gender',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='dan', max_length=100),
            preserve_default=False,
        ),
    ]
